name: cicd

on:
  push:
    branches:
      - main

jobs:
  doeverything:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: aws config
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: zip project
        run: |
          zip -r website.zip *

      - name: copy zip to s3
        run: |
          aws s3 cp website.zip s3://finalexams3/website.zip --region us-east-1

      - name: create app from s3
        run: |
          aws elasticbeanstalk create-application-version --application-name reactapp --version-label reactapp-v1 --region us-east-1 --source-bundle S3Bucket=finalexams3,S3Key=website.zip --auto-create-application

      - name: install eb
        run: |
          pip install awsebcli --upgrade --user

      - name: deploy app to eb
        run: |
          eb init -i reactapp -k assignment-02-kp -p Docker --region us-east-1
          eb deploy Reactapp-env --version reactapp-v1
